# Week 3 Assignment

## Task 1

In [1]:
class Book:
    def __init__(self, title, author, pages):
        """
        Initializes a Book object with title, author, and pages.
        """
        self._title = title
        self._author = author
        self._pages = pages

    def get_title(self):
        """Getter method for title"""
        return self._title

    def set_title(self, title):
        """Setter method for title"""
        self._title = title

    def get_author(self):
        """Getter method for author"""
        return self._author

    def set_author(self, author):
        """Setter method for author"""
        self._author = author

    def get_pages(self):
        """Getter method for pages"""
        return self._pages

    def set_pages(self, pages):
        """Setter method for pages"""
        self._pages = pages

    @classmethod
    def calculate_reading_time(cls, pages, reading_speed=250):
        """
        Calculates the reading time in minutes based on the number of pages and reading speed.
        """
        return pages / reading_speed

    def __str__(self):
        """
        Returns a string representation of the Book object.
        """
        return f"Title: {self._title}, Author: {self._author}, Pages: {self._pages}"


class Ebook(Book):
    def __init__(self, title, author, pages, format):
        """
        Initializes an Ebook object with title, author, pages, and format.
        """
        super().__init__(title, author, pages)
        self._format = format

    def get_format(self):
        """Getter method for format"""
        return self._format

    def set_format(self, format):
        """Setter method for format"""
        self._format = format

    def __str__(self):
        """
        Returns a string representation of the Ebook object.
        """
        return f"{super().__str__()}, Format: {self._format}"


# Example usage
book = Book("To Kill a Mockingbird", "Harper Lee", 281)
print(book)
print(f"Reading time: {Book.calculate_reading_time(book.get_pages())} minutes")

ebook = Ebook("The Great Gatsby", "F. Scott Fitzgerald", 180, "EPUB")
print(ebook)
print(f"Reading time: {Book.calculate_reading_time(ebook.get_pages())} minutes")

Title: To Kill a Mockingbird, Author: Harper Lee, Pages: 281
Reading time: 1.124 minutes
Title: The Great Gatsby, Author: F. Scott Fitzgerald, Pages: 180, Format: EPUB
Reading time: 0.72 minutes


# Library Management System
## Book Class
#### Attributes
* `title`: The title of the book
* `author`: The author of the book
* `pages`: The number of pages in the book

#### Methods
* `get_title()`: Returns the title of the book
* `set_title(title)`: Sets the title of the book
* `get_author()`: Returns the author of the book
* `set_author(author)`: Sets the author of the book
* `get_pages()`: Returns the number of pages in the book
* `set_pages(pages)`: Sets the number of pages in the book
* `calculate_reading_time(pages, reading_speed=250)`: Calculates the reading time in minutes based on the number of pages and reading speed (default is 250 words per minute)
* `__str__()`: Returns a string representation of the Book object

## Ebook Class
#### Inherits from
* `Book` class

#### Attributes
* `format`: The format of the ebook (e.g. EPUB, PDF, MOBI)

#### Methods
* `get_format()`: Returns the format of the ebook
* `set_format(format)`: Sets the format of the ebook
* `__str__()`: Returns a string representation of the Ebook object, including all attributes from the `Book` class and the `format` attribute

## Example Usage
#### Book Object
* Creates a `Book` object with title "To Kill a Mockingbird", author "Harper Lee", and 281 pages
* Prints the book details using the `__str__()` method
* Calculates the reading time using the `calculate_reading_time()` method

#### Ebook Object
* Creates an `Ebook` object with title "The Great Gatsby", author "F. Scott Fitzgerald", 180 pages, and format "EPUB"
* Prints the ebook details using the `__str__()` method
* Calculates the reading time using the `calculate_reading_time()` method


# Task 2

In [4]:
def read_file(filename):
    """
    Reads data from a text file and prints its contents.
    """
    try:
        with open(filename, 'r') as file:
            data = file.read()
            print(data)
            return data
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    except Exception as e:
        print(f"Error: {e}")

def count_words(filename):
    """
    Counts the number of words in a file and prints the result.
    """
    data = read_file(filename)
    if data:
        words = data.split()
        print(f"Number of words: {len(words)}")

def write_file(filename):
    """
    Writes user input to a new file and handles exceptions related to file writing.
    """
    try:
        with open(filename, 'w') as file:
            user_input = input("Enter text to write to file: ")
            file.write(user_input)
            print(f"Data written to {filename}")
    except Exception as e:
        print(f"Error: {e}")

# Example usage
read_file('data.txt')
count_words('data.txt')
write_file('output.txt')

This is a sample text file for demonstration purposes.
It contains some random words and sentences to test the file handling program.
The program will read this text, count the number of words, and write user input to a new file.
This is the end of the sample text.
This is a sample text file for demonstration purposes.
It contains some random words and sentences to test the file handling program.
The program will read this text, count the number of words, and write user input to a new file.
This is the end of the sample text.
Number of words: 49
Enter text to write to file: This is the text for the output file.
Data written to output.txt


# File Handling Program
## Overview
This program demonstrates file handling in Python, including reading from a file, counting the number of words, and writing user input to a new file.

## Functions
### `read_file(filename)`
 Reads data from a text file and prints its contents.
#### Parameters
* `filename`: The name of the file to read from.

#### Exceptions
* `FileNotFoundError`: If the file is not found.
* `Exception`: For any other errors while reading from the file.

### `count_words(filename)`
Counts the number of words in a file and prints the result.
#### Parameters
* `filename`: The name of the file to count words from.

### `write_file(filename)`
Writes user input to a new file and handles exceptions related to file writing.
#### Parameters
* `filename`: The name of the file to write to.

## Example Usage
The program reads data from `data.txt`, counts the number of words, and writes user input to `output.txt`.


# Task 3

In [6]:
# mathpkg/addition.py

def add(a, b):
    """
    Returns the sum of a and b.
    """
    return a + b


# mathpkg/subtraction.py

def subtract(a, b):
    """
    Returns the difference of a and b.
    """
    return a - b


# mathpkg/multiplication.py

def multiply(a, b):
    """
    Returns the product of a and b.
    """
    return a * b



# mathpkg/division.py

def divide(a, b):
    """
    Returns the division of a by b.
    Raises ZeroDivisionError if b is zero.
    """
    if b == 0:
        raise ZeroDivisionError("division by zero")
    return a / b



# mathpkg/modulus.py

def modulus(a, b):
    """
    Returns the modulus of a and b.
    """
    return a % b


# mathpkg/exponentiation.py

def power(a, b):
    """
    Returns a raised to the power of b.
    """
    return a ** b


# mathpkg/square_root.py

import math

def square_root(a):
    """
    Returns the square root of a.
    Raises ValueError if a is negative.
    """
    if a < 0:
        raise ValueError("square root not defined for negative numbers")
    return math.sqrt(a)


# this is combined code of task 3 for explaination and distributed  code on difference .py files.

# main.py

#from math.addition import add
#from math.subtraction import subtract
#from math.multiplication import multiply
#from math.division import divide
#from math.modulus import modulus
#from math.exponentiation import power
#from math.square_root import square_root

def main():
    try:
        # Demonstrate addition
        print("Addition: 5 + 3 =", add(5, 3))
        
        # Demonstrate subtraction
        print("Subtraction: 5 - 3 =", subtract(5, 3))
        
        # Demonstrate multiplication
        print("Multiplication: 5 * 3 =", multiply(5, 3))
        
        # Demonstrate division
        print("Division: 5 / 3 =", divide(5, 3))
        
        # Demonstrate modulus
        print("Modulus: 5 % 3 =", modulus(5, 3))
        
        # Demonstrate exponentiation
        print("Exponentiation: 5 ** 3 =", power(5, 3))
        
        # Demonstrate square root
        print("Square Root: sqrt(25) =", square_root(25))

        # Handle potential errors
    except ZeroDivisionError as e:
        print(e)
    except ValueError as e:
        print(e)

if __name__ == "__main__":
    main()

Addition: 5 + 3 = 8
Subtraction: 5 - 3 = 2
Multiplication: 5 * 3 = 15
Division: 5 / 3 = 1.6666666666666667
Modulus: 5 % 3 = 2
Exponentiation: 5 ** 3 = 125
Square Root: sqrt(25) = 5.0


# Math Package
## Overview
The `math` package contains modules for basic arithmetic operations and advanced mathematical operations.

## Modules
### `addition.py`
Contains the `add` function for adding two numbers.

### `subtraction.py`
Contains the `subtract` function for subtracting two numbers.

### `multiplication.py`
Contains the `multiply` function for multiplying two numbers.

### `division.py`
Contains the `divide` function for dividing two numbers. Raises `ZeroDivisionError` if the divisor is zero.

### `modulus.py`
Contains the `modulus` function for finding the modulus of two numbers.

### `exponentiation.py`
Contains the `power` function for raising a number to a power.

### `square_root.py`
Contains the `square_root` function for finding the square root of a number. Raises `ValueError` if the input is negative.

## `main.py` Script
Demonstrates importing and using functions from the `math` package. Handles potential errors using exception handling.

### Example Usage
```python
from math.addition import add
from math.subtraction import subtract
from math.multiplication import multiply
from math.division import divide
from math.modulus import modulus
from math.exponentiation import power
from math.square_root import square_root

print("Addition: 5 + 3 =", add(5, 3))
print("Subtraction: 5 - 3 =", subtract(5, 3))
print("Multiplication: 5 * 3 =", multiply(5, 3))
print("Division: 5 / 3 =", divide(5, 3))
print("Modulus: 5 % 3 =", modulus(5, 3))
print("Exponentiation: 5 ** 3 =", power(5, 3))
print("Square Root: sqrt(25) =", square_root(25))
Exception Handling
Python
try:
    # Code that may raise exceptions
except ZeroDivisionError as e:
    print(e)
except ValueError as e:
    print(e)
This program demonstrates the creation of a Python package math (mathpkg) with modules for basic arithmetic operations and advanced mathematical operations. The main.py script shows how to import and use these functions, with exception handling to catch and display errors.



# Task 4

In [7]:

class Countdown:
    
    def __init__(self, start):
        self.start = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.start < 1:
            raise StopIteration
        current = self.start
        self.start -= 1
        return current

def fibonacci_generator(limit):
    
    a, b = 0, 1
    while a <= limit:
        yield a
        a, b = b, a + b

def random_number_generator(start, end, count):
    
    import random
    for _ in range(count):
        yield random.randint(start, end)

def main():
    try:
        # Using the Countdown iterator
        countdown = Countdown(5)
        for num in countdown:
            print(num)

        # Using the fibonacci_generator
        fib_limit = 100
        fib_gen = fibonacci_generator(fib_limit)
        for num in fib_gen:
            print(num)

        # Using the random_number_generator
        start, end, count = 1, 100, 5
        rand_gen = random_number_generator(start, end, count)
        for num in rand_gen:
            print(num)

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

5
4
3
2
1
0
1
1
2
3
5
8
13
21
34
55
89
42
39
39
64
79


## Countdown Class
### This class acts as an iterator that counts down from a given start value to 1.
class Countdown:
    def __init__(self, start):
        # Initialize the countdown with a start value.
        self.start = start

    def __iter__(self):
        # The __iter__ method makes the class iterable.
        return self

    def __next__(self):
        # The __next__ method defines the iteration logic.
        # If the current value is less than 1, stop the iteration.
        if self.start < 1:
            raise StopIteration
        # Store the current value to return it, then decrement the start value.
        current = self.start
        self.start -= 1
        return current

## Fibonacci Generator Function
### This function generates Fibonacci numbers up to a given limit.
def fibonacci_generator(limit):
    # Initialize the first two Fibonacci numbers.
    a, b = 0, 1
    # Generate numbers as long as 'a' is less than or equal to the limit.
    while a <= limit:
        # Yield the current value of 'a'.
        yield a
        # Update 'a' and 'b' to the next two numbers in the sequence.
        a, b = b, a + b

## Random Number Generator Function
### This function generates a specified count of random numbers within a given range.
def random_number_generator(start, end, count):
    # Import the random module to generate random numbers.
    import random
    # Generate 'count' random numbers within the range [start, end].
    for _ in range(count):
        yield random.randint(start, end)

## Main Function
### This function demonstrates the usage of the above-defined classes and functions.
def main():
    try:
        # Using the Countdown iterator
        countdown = Countdown(5)
        # Iterate through the countdown and print each number.
        for num in countdown:
            print(num)

        # Using the fibonacci_generator
        fib_limit = 100
        fib_gen = fibonacci_generator(fib_limit)
        # Iterate through the Fibonacci generator and print each number.
        for num in fib_gen:
            print(num)

        # Using the random_number_generator
        start, end, count = 1, 100, 5
        rand_gen = random_number_generator(start, end, count)
        # Iterate through the random number generator and print each number.
        for num in rand_gen:
            print(num)

    except Exception as e:
        # If an exception occurs, print the error message.
        print(f"Error: {e}")
